name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Flet CLI
        run: |
          pip install flet
          
      - name: Install Dependencies from requirements
        run: |
          pip install -r requirements.txt
          
      - name: Build IPA File
        run: |
          # Команда для создания IPA без подписи (для TrollStore)
          flet build ipa --no-codesign
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pustota-App
          path: build/ipa/*.ipa
