name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Setup
        run: |
          python3 -m pip install flet flet-audio-recorder
          [ -f requirements.txt ] && pip install -r requirements.txt || echo "No requirements"
      - name: Build
        run: |
          # Собираем приложение
          flet build ipa --no-codesign
      - name: Force Collect IPA
        run: |
          # Создаем папку и ПРИНУДИТЕЛЬНО копируем туда найденный файл
          mkdir -p final_output
          find . -name "*.ipa" -exec cp {} final_output/ \;
          ls -R final_output
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Pustota-App
          path: final_output/*.ipa
